### ISSUE TITLE
Pipelines view: show downstream jobs

### ISSUE THREAD

**Issue by TomasTomecek** [packit/dashboard#187]
I'd love to see all the downstream bodhi update creations and koji builds that Packit did in the generic Pipelines view.

* [x] packit/dashboard#199
* [x] packit/packit-service#1889
* [x] packit/dashboard#214
* [x] packit/packit-service#1890
* [x] packit/packit-service#1891
* [x] packit/dashboard#215

---

* What are the Benefits:
  * Downstream jobs are visible from a single view. Users can see the state/logs of the job and is able to access related objects/jobs.
  * Packit project can show the usage of the service.
* Who will benefit: 
  * All Fedora maintainers using Packit

**Comment by lbarcziova** [comment]
With growing user base of downstream jobs, this would be really beneficial, see packit/packit#2093.

**Comment by lachmanfrantisek** [comment]
Another benefit of having this is that we can track the onboarding progress more easily.

**Comment by TomasTomecek** [comment]
agreed, sounds like a good epic for Q4 :)

**Comment by lbarcziova** [comment]
This is now finished 🎉
