### ISSUE TITLE
Filtering

### ISSUE THREAD

**Issue by lbarcziova** [packit/dashboard#468]
This is a tracking epic for the multiple efforts to improve the UX of our dashboard.

What should be done:
- [x] packit/packit-service#2699
- [ ] packit/packit-service#2567
- [ ] packit/packit-service#1882, as a part of this possible DB improvements 
- [ ] packit/packit-service#2513
- [ ] #257

**Comment by Venefilyn** [comment]
I would love if we can try to do this as part of a migration to FastAPI, which should be possible to do over time given that FastAPI can serve Flask

That way we can also change the current structure to enforce syntax that enables Swagger auto-generation. I know @majamassarini tried a while back to marshal all the endpoints but it created a lot of duplication

With FastAPI or doing a huge refactor of the current View-Model we can sort this out, making filtering a lot easier. I noticed there is a lot of technical debt as well with the API views as they generate a lot of queries for each request and do a lot of the heavy lifting inside the view rather than in the model - which makes things a lot less maintainable and less performant
